### ISSUE TITLE
Transaction.hash() doesn't match after toRaw()/fromRaw

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-core#103]
This happens for spending condition with `signAll()`

**Comment by sunify** [comment]
On which branch? Works fine on master https://github.com/leapdao/leap-core/blob/master/lib/transaction.spec.js#L281

**Comment by pinkiebell** [comment]
@sunify Yes, I think that was because of a stale `node_modules` at the time I was working on integration tests 😏
