### ISSUE TITLE
simplify proof generation by using period store

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-core#115]
## Bounty

the [period store](https://github.com/leapdao/leap-node/issues/289) is meant to reduce the complexity to create proofs for transaction inclusion. 

## Scope
- change current `getProof()` to use period store
- do not require `slotId` or `validatorAddr` as inputs for proof generation

## Deliverables
- code
- test

## Gain for the project
- run multiple validators

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

**Comment by troggy** [comment]
@johannbarbie is it a bounty? If so, what are the numbers?

**Comment by johannbarbie** [comment]
yes, let's make it a bounty. you know the effort of it?

**Comment by troggy** [comment]
XS
