### ISSUE TITLE
get rid of node-fetch dependency

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-core#149]

**Comment by sunify** [comment]
Why?

**Comment by troggy** [comment]
It is an extra dependency needed only for a very niche feature (fast exit). E.g. we are using leap-core in many scripts just for crunching data and have to drag node-fetch as well.

Probably, the better solution would be to extract exit market maker things in a separate package

On a bright side, node-fetch has no dependencies itself 🎉, so maybe not a big deal.

**Comment by sunify** [comment]
https://bundlephobia.com/result?p=node-fetch@2.6.0 441B in a bundle for browsers 🤷‍♂

**Comment by troggy** [comment]
best package ever :)
