### ISSUE TITLE
Add prevHash to period proof

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-core#165]
# Bounty

Needed for [heartbeat challenge](https://github.com/leapdao/leap-contracts/pull/258) and [injecting time and blockhash](https://github.com/leapdao/leap-node/issues/182) into execution environment for spendies

## Scope
- append period prevHash to proof structure 
- update unit tests

## Deliverables
- updated code
- updated tests

## Gain for the project
- abilitity to reference time and blockhash in spendies
- ability to verify validator heartbeats

## Roles
bounty gardener: @troggy / share
bounty worker: @TheReturnOfJan  / share
bounty reviewer: name / share

## Funded by

Dev Circle

**Comment by TheReturnOfJan** [comment]
Im taking this.

**Comment by troggy** [comment]
@TheReturnOfJan this thing is not a bounty yet. How big do you estimate it is?

**Comment by TheReturnOfJan** [comment]
S

**Comment by troggy** [comment]
@TheReturnOfJan are you working on this? 🤔

**Comment by TheReturnOfJan** [comment]
On it.
