### ISSUE TITLE
Fail in leap-core test.

### ISSUE THREAD

**Issue by securekim** [leapdao/leap-core#36]
I got an error (transaction) :

**command : yarn test
node version : 8.10.0**

  1) transactions
       should allow to sign with web3:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/brokim/workspace/leapdao/leap-core/lib/transaction.spec.js)

I Change this to below, error is gone. please check it.

![2019-01-10 00-24-52](https://user-images.githubusercontent.com/35220663/50909032-4fd79f80-146e-11e9-9e21-86cd8c0d3dd0.png)

**Comment by johannbarbie** [comment]
@securekim i couldn't reproduce your error, but i've mocked out the dependency, can you try the same with this code? https://github.com/leapdao/leap-core/pull/37

**Comment by securekim** [comment]
Problem is solved with #37 . Thank you.
