### ISSUE TITLE
Allow for read-only inputs for spending conditions

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-core#39]
Spending conditions that only read data from tokens do not need to consume the UTXO. Inputs that only read need to be distinguishable from inputs that modify the UTXO-state, so that they can not be used in exit-challenges. see details here: https://docs.google.com/drawings/d/1bDlF7ORgQ4W1pkMNk0MoUb6nQFEq72f9ZjBVsKBvbyE

**Comment by troggy** [comment]
not needed: https://leapdao.slack.com/archives/CAAGW85BR/p1557494431047600
