### ISSUE TITLE
Use BigInt to represent value of ERC20 outputs

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-core#48]
## Scope 
- rewrite, ideally including `jsbi`. 
- make sure to test in node, bridge-ui and mobile wallet

## Deliverables
- code
- shim for frontend projects

## Gain for the project
- ability to avoid rounding errors

## Bounty

gardener: @johannbarbie | 10%
worker: @troggy | 70%
reviewer: @eezcjkr | 20%

**Comment by troggy** [comment]
make sure to test in
-[ ] node, 
-[ ] bridge-ui
-[ ] mobile wallet
