### ISSUE TITLE
Add EIP712 support

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-core#49]
I guess there is ~some~ support for it in a current Metamask

I would be super nice to use it for signing plasma transactions — right now we are asking user to sign some unreadable stuff.

Reference:
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md
https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26

**Comment by sunify** [comment]
Doesn't seem possible without changing everything — core and contracts. So i'll close it for better times
