### ISSUE TITLE
split spending conditions into 2 versions

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-core#73]
this created a hardfork change: https://github.com/leapdao/leap-core/pull/71

scope:
extract changes into it's own tx-type (`SPEND_COND` & `SPEND_COND2`)

delivery:
- have chains with `SPEND_COND` type pass synchronization
- prevent inclusion of `SPEND_COND` in new blocks
- use `SPEND_COND2` for all new spending conditions

**Comment by eshavkun** [comment]
Con we rename old one to `SPEND_COND_LEGACY` or smth? I don't like the numbers... :)

**Comment by johannbarbie** [comment]
the type is a number, so i guess yes

**Comment by zyfrank** [comment]
@johannbarbie @eshavkun  Can I take this one?

**Comment by johannbarbie** [comment]
outdated
