### ISSUE TITLE
Support for proper bundling for in the `dist` step

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/leap-core#82]
# Bounty
Use `gulp` or something similar to bundle the distribution js files,
to make it outright usable to `<script src...>` it :)

## Scope
- bundling

## Deliverables
Super convenient way to add leap-core support to a webpage

## Gain for the project
🌮 

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

**Comment by troggy** [comment]
+ polyfill for Buffer https://github.com/feross/buffer
