### ISSUE TITLE
allow spending-condition to pull funds

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-core#90]
# Bounty

```
+--------------------+      +--------+
|address: spend_cond |  <---+prevout |
|value:  5/6         |      |script  +-+    +--------------------+
+--------------------+      |msgData | +----+address: spend_cond |
                            +--------+ |    +value:  6/6         |
                                       |    +--------------------+
+--------------------+      +--------+ |
|address: user       |  <---+prevout +-+
|value:  1/6         |      |sigUser |
+--------------------+      +--------+
```
if a user wants to send funds to a spending condition, the user should be able to point to one of his outputs and sign it. in the spending condition it should produce an allowance:
```

address constant token = 0x11;
address constant user = 0x22;
function fulfill() public {
  token = ERC20(token);
  uint256 amount = token.allowance(user, address(this));
  token.transferFrom(user, address(this), amount);
}
```

## Scope
- ability to sign secondary inputs
- no breaking changes

## Deliverables
- code
- tests
- documentation

## Gain for the project
- spending conditions to pull funds

## Roles
bounty gardener: @johannbarbie / 15%
bounty worker: name / share
bounty reviewer: name / share

**Comment by pinkiebell** [comment]
Note: do the sig over the full transaction because of security reasons.

**Comment by pinkiebell** [comment]
@johannbarbie The no-breaking-changes might not be possible now 😁

**Comment by troggy** [comment]
@johannbarbie is this implemented already? I barely followed the changes for Dungeons

**Comment by johannbarbie** [comment]
yes, it is already in here: https://github.com/leapdao/leap-core/pull/99
