### ISSUE TITLE
Replace color with contract address of root chain

### ISSUE THREAD

**Issue by TimDaub** [leapdao/leap-core#96]
I'm not totally familiar with the choices that lead to the `color` attribute, but I'd still like to propose a change.

Right now, every token gets assigned a color when deposited to the plasma chain. As far as I understand, it's an ID that keeps track of the token.
When using leap-core, one has to then specify the color to the transferred in a call. Additionally, there's a `getColor` function call that returns the color of a token given its contract address.

My proposal is to remove `color` completely, and instead use the contract address of the token on the root chain as the ID of the token on the plasma chain. This would reduce the number of calls required to make a transaction, simplify leap-core code and make it easier for a developer to write code with leap-core.

**Comment by pinkiebell** [comment]
This is booth a usability improvement and architecture improvement overall +1

**Comment by sunify** [comment]
And probably too late to happen

**Comment by troggy** [comment]
On a brighter side, colors make raw outputs smaller in size

**Comment by troggy** [comment]
How to make it in a backward compatible fashion: change all the RPC to accept `colorOrAddress` instead of `color`. This should be done on the leap-node side then

**Comment by troggy** [comment]
Addressing here: https://github.com/leapdao/leap-node/issues/325

**Comment by troggy** [comment]
- [x] implemented leapdao/leap-node#325
- [ ] available on the testnet
- [ ] available on the mainnet

**Comment by johannbarbie** [comment]
are we still planning to change the structure of the transactions and replace color with address there?

**Comment by troggy** [comment]
I think that https://github.com/leapdao/leap-node/issues/325 is good enough. @TimDaub what do you think? Does it solve your problem?

**Comment by sunify** [comment]
It would be insane to change the structure at this point, anyway. So i close the issue until something will change

**Comment by johannbarbie** [comment]
@sunify love the attitude :)
